/**
 * uiActionRegistry.js
 * 
 * Maps declarative UI actions generated by the Mitra Voice Assistant (Backend)
 * to actual React navigation and DOM events.
 */

export const executeUiAction = (action, navigate) => {
    if (!action || !action.type) return;

    console.log("[Mitra UI Action]", action);

    switch (action.type) {
        case 'OPEN_DASHBOARD':
        case 'OPEN_FARMS':
            navigate('/my-farms');
            break;
            
        case 'OPEN_FARM':
            navigate(`/my-farms`); // Add logic if the route uses URL params or state
            // Dispatch event for the MyFarms component to open the specific farm
            setTimeout(() => {
                window.dispatchEvent(new CustomEvent('mitraOpenFarm', { detail: action }));
            }, 500);
            break;
            
        case 'OPEN_SCANNER':
            navigate('/pest-prediction');
            break;
            
        case 'OPEN_NEW_FARM_MODAL':
            navigate('/my-farms');
            setTimeout(() => {
                window.dispatchEvent(new CustomEvent('mitraOpenNewFarmModal', { detail: action }));
            }, 500);
            break;
            
        case 'MAP_FOCUS':
            window.dispatchEvent(new CustomEvent('mitraMapFocus', { detail: action }));
            break;
            
        case 'HIGHLIGHT_ELEMENT':
            window.dispatchEvent(new CustomEvent('mitraHighlightElement', { detail: action }));
            break;
            
        case 'SET_FORM_VALUE':
            window.dispatchEvent(new CustomEvent('mitraSetFormValue', { detail: action }));
            break;
            
        default:
            console.warn("Unknown UI action from Mitra:", action);
    }
};
